<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cari_mr-2</name>
   <tag></tag>
   <elementGuidId>bccc13f1-fee2-4439-9bb0-aa6cc7b8af0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://jne.terralogiq.net/jne-frontend/assets/image/ic-find.png')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://jne.terralogiq.net/jne-frontend/assets/image/ic-find.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid body&quot;]/div[@class=&quot;main-content pt-5 mt-5&quot;]/div[@class=&quot;advance_search_sales mt-3 p-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 pl-4 pr-4&quot;]/div[@class=&quot;form-group pl-5 pr-5 mt-5&quot;]/button[@class=&quot;btn btn-outline-light rounded-pill px-4 btn-searching-sales&quot;]/img[@class=&quot;mr-2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://jne.terralogiq.net/jne-frontend/assets/image/ic-find.png')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img</value>
   </webElementXpaths>
</WebElementEntity>
