<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mei 2019_m-auto</name>
   <tag></tag>
   <elementGuidId>bd9a8d62-811b-45a8-ad69-bc36ccadbdeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://jne.terralogiq.net/jne-frontend/assets/image/ic-cms.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://jne.terralogiq.net/jne-frontend/assets/image/ic-cms.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;body&quot;]/div[@class=&quot;main-navbar&quot;]/nav[@class=&quot;navbar fixed-top navbar-light bg-light justify-content-between p-0 pr-3 small&quot;]/div[@class=&quot;d-flex menu-wrapper-left&quot;]/a[1]/div[@class=&quot;menu-header-left d-flex&quot;]/img[@class=&quot;m-auto&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://jne.terralogiq.net/jne-frontend/assets/image/ic-cms.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
